## Hooks

### 05. useEffect() 내부의 비동기

---

```jsx
// useEffect() 내부의 비동기
// ❌
useEffect(async () => {
  // 비동기 작업
  const result = await fetchData();
}, []);

// ✅ ⬇️
useEffect(() => {
  const fecthData = async () => {
    const result = await someFetch();
  };

  fetchData();
}, [dependency]);
```

`useEffect` 안에서 `비동기 함수` 는 사용이 불가능하다. 요즘은 `tanstack query` 등을 통해서 데이터 통신 하는것을 권하고 있다.

심지어 `vercel` 의 등장으로 `nextjs` 와 연관된 발전이 지속적으로 이어지고 있다.

✅ 일단은 `async / await` 같은 것들은 `useEffect` 내부에서 사용할 수가 없다.

`'await' is only allowed within async functions`

보통 이런 에러를 볼 수 있다.
useEffect의 첫번째 인자로 `실행될 callback` / 두번째 인자로 `의존성을 가진 상태` 를 넣는데 첫번째 인자로 `async / await` 를 넣을 수 없는 것이다

#### 왜?

`useEffect` 는 `반환 타입` 으로 `함수 / undefined / ... ` 를 허용하지만 `Promise` 를 반환으로 활용하는 `async / await` 랑 완전히 일치하지 않다.

그렇기 때문에 비동기 함수를 호출하면 예상치 못하게 제어하지 못하는 코드가 지속적으로 실행될 수 있기 때문에 `useEffect` 내부에서 `async / await , promise` 를 사용할때에 주의해야한다는 에러를 보여준다.

불편하지만 `callback` 함수는 `일반적인 함수` 를 넘겨주되 이 내부에서 `async / await` 혹은 `즉시실행함수` 를 호출해야 한다.

### 📌 정리

> ✅ 그냥 안된다고 생각하기보다 `useEffect` 내부에서 비동기를 사용하는 것이 불안한 작업임을 인지하고 있자. 매번 비동기 작업을 useEffect로 처리하면 제어하기 어렵다.
